floss: Fix -Wmissing-template-arg-list-after-template-kw warning
With llvm-r547379-1, the following warning is issued:

    In file included from .../ext/filters/client_channel/channel_connectivity.cc:31:
    In file included from .../ext/filters/client_channel/client_channel.h:40:
    In file included from .../ext/filters/client_channel/client_channel_factory.h:24:
    In file included from .../ext/filters/client_channel/subchannel.h:35:
    In file included from .../ext/filters/client_channel/connector.h:31:
    In file included from .../lib/transport/transport.h:58:
    In file included from .../lib/promise/pipe.h:43:
    In file included from .../lib/promise/seq.h:23:
    .../lib/promise/detail/basic_seq.h:474:38: error: a template argument
    list is expected after a name prefixed by the template keyword
    [-Wmissing-template-arg-list-after-template-kw]
      474 |                     Traits::template CallSeqFactory(f_, *cur_, std::move(arg)));
          |                                      ^
    1 error generated.

Apply an upstream patch from the embedded grpc library:

    Clang now requires a template argument list after the use of the
    template keyword. Edit this instance to remove the template keyword
    since there are no template arguments.

    See https://github.com/llvm/llvm-project/pull/80801.

See https://github.com/grpc/grpc/pull/36805

Change-Id: I54d8680f34338e5faea7278a0f4a99469f406e60

BUG=b:368393962
TEST=emerge-jacuzzi third-party-crates-src floss

Change-Id: I5f222e78132f2a7fae0ad106250688c095e294e0
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/rust_crates/+/6075068
Tested-by: Andrej Shadura <andrew.shadura@collabora.com>
Reviewed-by: Allen Webb <allenwebb@google.com>
Commit-Queue: Andrej Shadura <andrew.shadura@collabora.com>
Reviewed-by: George Burgess <gbiv@chromium.org>